services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  data: