services:
  redis:
    build:
      context: ./config/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - dist:/usr/share/nginx/html
    ports:
      - "80:80"

  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
      target: builder
    container_name: node
    command: ["/bin/true"]
    volumes:
      - dist:/app/dist

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - redis

volumes:
  data:
  dist: