
- name: Install docker
  ansible.builtin.apt:
    name: '{{ docker_packages }}'
    state: present
    update_cache: true

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    group: docker
    append: true
