---
- name: Install dependencies
  ansible.builtin.import_tasks: install_packages.yml

- name: Set timezone
  ansible.builtin.import_tasks: timezone.yml

- name: Set hostname
  ansible.builtin.import_tasks: hostname.yml

- name: Add official docker repository
  ansible.builtin.import_tasks: docker_repo.yml

- name: Install docker
  ansible.builtin.import_tasks: docker_packages.yml
